# vm_config.yml
vm_name: "Debian12VM"
os_type: "Debian_64"
memory: 4096
cpus: 2
vram: 128
nic: "bridged"
vdi_size: 50000
iso_url: "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.1.0-amd64-netinst.iso"
iso_download_path: "C:/VirtualBox VMs/Debian12VM/debian-12.iso"
disk_filename: "C:/VirtualBox VMs/Debian12VM/Debian12VM.vdi"
preseed_file: "./preseed.cfg"  # Der Pfad zur Preseed-Datei auf dem Ansible-Host
